//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookBookApp
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class RecipeIngredient
    {
        public int RecipeID { get; set; }
        public string Name { get; set; }
        public int IngredientID { get; set; }
        public string Measure { get; set; }
        public string Quantity { get; set; }
        public string PreparationNotes { get; set; }
        public int ID { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
